### ISSUE TITLE
The Layout

### ISSUE THREAD

**Issue by ZijunXia** [JattMones/mattjonesofficial.github.io#1]
## Firstly, this is a very great website, it has everything that required on the assignment, like the introduction part and links to github and LinkedIn(I found I can not open the LinkedIn page). I think if the author can make more blank parts upon the links, which means let the links part always on the bottom of the website, that should be better.

**Comment by JattMones** [comment]
I don't think the extra spaces are really needed, thanks for the suggestion though. I did try address the linkedIn issue in my commits, thanks!
